ga_views:
  wwatch: "18857756"
  gwwatch: '77121234'
  nwisweb_desktop: '49785472'
  
ga_token: '~/.vizlab/VIZLAB-a48f4107248c.json'

url_sheet_name: 'Watches url mapping'

palette: 
  ww: '#8da0cb'
  gww: '#66c2a5'
  wqw: '#fc8d62'  #in order for WW, GWW, WQW
